name: superheroes
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rxdart: ^0.27.3
  provider: ^6.0.2
  google_fonts: ^2.3.1
  http: ^0.13.4
  flutter_dotenv: ^5.0.2
  json_annotation: ^4.4.0
  cached_network_image: ^3.2.0
  shared_preferences: ^2.0.13
  golden_toolkit: ^0.13.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  network_image_mock: ^2.0.1
  build_runner: ^2.1.8
  json_serializable: ^6.1.5


flutter:


  uses-material-design: true
  assets:
    - google_fonts/
    - assets/images/
    - assets/icons/
    - .env

